export const EmptyPortfolio = {
  name: '',
  baseCoin: {
    symbol: '',
    address: '',
    chainId: 0,
    coinId: '',
    decimals: 0,
    graphAddress: '',
    isMain: false,
    isStable: false,
    logoURI: '',
    name: '',
    onramper: false,
    onrapmerId: '',
    priceChange1h: 0,
    priceChange24h: 0,
    priceChange30d: 0,
    priceChange7d: 0,
    usdPrice: 0,
    marketCap: 0,
    volume24h: 0,
    id: '',
  },
  stableCoin: {
    symbol: '',
    address: '',
    chainId: 0,
    coinId: '',
    decimals: 0,
    graphAddress: '',
    isMain: false,
    isStable: false,
    logoURI: '',
    name: '',
    onramper: false,
    onrapmerId: '',
    priceChange1h: 0,
    priceChange24h: 0,
    priceChange30d: 0,
    priceChange7d: 0,
    usdPrice: 0,
    marketCap: 0,
    volume24h: 0,
    id: '',
  },
  coins: [
    {
      coin: {
        symbol: '',
        address: '',
        chainId: 0,
        coinId: '',
        decimals: 0,
        graphAddress: '',
        isMain: false,
        isStable: false,
        logoURI: '',
        name: '',
        onramper: false,
        onrapmerId: '',
        priceChange1h: 0,
        priceChange24h: 0,
        priceChange30d: 0,
        priceChange7d: 0,
        usdPrice: 0,
        marketCap: 0,
        volume24h: 0,
        id: '',
      },
      percentage: '10',
      amount: 0,
      avgPrice: 0,
    },
  ],
  id: '',
};
