const fonts = {
  Bellota: 'Bellota-Bold',
  Poppins: [
    'Poppins-Regular',
    'Poppins-Black',
    'Poppins-Bold',
    'Poppins-BoldItalic',
    'Poppins-ExtraBold',
    'Poppins-ExtraBoldItalic',
    'Poppins-ExtraLight',
    'Poppins-ExtraLightItalic',
    'Poppins-Italic',
    'Poppins-Light',
    'Poppins-LightItalic',
    'Poppins-Medium',
    'Poppins-MediumItalic',
    'Poppins-SemiBold',
    'Poppins-SemiBoldItalic',
    'Poppins-Thin',
    'Poppins-ThinItalic',
  ],
  PlusJakartaSans: [
    'PlusJakartaSans-Bold',
    'PlusJakartaSans-BoldItalic',
    'PlusJakartaSans-ExtraBold',
    'PlusJakartaSans-ExtraBoldItalic',
    'PlusJakartaSans-ExtraLight',
    'PlusJakartaSans-ExtraLightItalic',
    'PlusJakartaSans-Italic',
    'PlusJakartaSans-Light',
    'PlusJakartaSans-LightItalic',
    'PlusJakartaSans-Medium',
    'PlusJakartaSans-MediumItalic',
    'PlusJakartaSans-Regular',
    'PlusJakartaSans-SemiBold',
    'PlusJakartaSans-SemiBoldItalic',
  ],
};

module.exports = fonts;
